http:
  port: "8888"
  prometheus:
    port: "9102"

grps:
  port: "50051"

db:
  host: "postgres"
  port: "5432"
  dbname: "calendar"
  user: "otus"
  password: "1234"
  connect_retries: 20
  prometheus:
    port: "9103"

notification:
  queue:
    host: "rabbit"
    port: "5672"
    user: "guest"
    password: "guest"
    qname: "events"
    connect_retries: 30
  scheduler:
    scan_timeout: "5s"
  sender:
    prometheus:
      port: "9104"

logger:
  level: "debug"
  output_paths:
    - stderr
    - /tmp/calendar/outlog
  error_output_paths:
    - stderr
    - /tmp/calendar/errlog

app:
  timezone: "Europe/Moscow"